from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, LabelViewSet

# Initialize a default router.
router = DefaultRouter()

# Register viewsets with the router. The first argument 'tasks' and 'labels'
# specifies the URL prefix for the routes associated with each viewset.
router.register(r'tasks', TaskViewSet)
router.register(r'labels', LabelViewSet)

# URL patterns are defined here. Including router.urls incorporates
# all the routes generated by the registered viewsets into the project.
urlpatterns = [
    path('', include(router.urls)),
]
